type CurrencyPair =
  | 'usd-rub'
  | 'eur-rub'
  | 'brl-rub'
  | 'kzt-rub'
  | 'idr-rub'
  | 'rub-usd'
  | 'eur-usd'
  | 'brl-usd'
  | 'kzt-usd'
  | 'idr-usd'
  | 'rub-eur'
  | 'usd-eur'
  | 'brl-eur'
  | 'kzt-eur'
  | 'idr-eur'
  | 'rub-brl'
  | 'usd-brl'
  | 'eur-brl'
  | 'kzt-brl'
  | 'idr-brl'
  | 'rub-kzt'
  | 'usd-kzt'
  | 'eur-kzt'
  | 'brl-kzt'
  | 'idr-kzt'
  | 'rub-idr'
  | 'usd-idr'
  | 'eur-idr'
  | 'brl-idr'
  | 'kzt-idr'

export type ExchangeRates = Record<CurrencyPair, number>
